image: node:16

stages:
  - test
  - report

variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - node_modules/

test:
  stage: test
  script:
    - npm ci
    - npx playwright install --with-deps
    - npm install -D @playwright/test allure-playwright
    - npx playwright test --reporter=line,allure-playwright
  artifacts:
    when: always
    paths:
      - allure-results
    expire_in: 1 week

generate_report:
  stage: report
  image: frankescobar/allure-docker-service
  script:
    - allure generate allure-results -o allure-report --clean
  artifacts:
    when: always
    paths:
      - allure-report
    expire_in: 1 week

pages:
  stage: report
  needs: ['generate_report']
  script:
    - mv allure-report public
  artifacts:
    paths:
      - public
  only:
    - master
