image: mcr.microsoft.com/playwright:v1.32.0-focal

stages:
  - test
  - report

variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - node_modules/

before_script:
  - npm ci

test:
  stage: test
  script:
    - npx playwright test --reporter=line,allure-playwright
  artifacts:
    when: always
    paths:
      - allure-results
      - playwright-report
    expire_in: 1 week
  allow_failure: true

generate_report:
  stage: report
  image: frankescobar/allure-docker-service
  script:
    - allure generate allure-results -o allure-report --clean
  artifacts:
    when: always
    paths:
      - allure-report
    expire_in: 1 week
  allow_failure: true

pages:
  stage: report
  needs: ['generate_report']
  script:
    - mv allure-report public
  artifacts:
    paths:
      - public
  only:
    - master